name: FastAPI App Testing

on:
    push: 
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
             # Step 1: Checkout the repo
            - name: Gives ability to checkout our repository
              uses: actions/checkout@v4
            # Step 2: Set up Python environment
            - name: Initializing python version 3.10
              uses: actions/setup-python@v4
              with: 
                python-version: "3.10"
            # Step 3: Installing Dependencies Flake 8 for linting, pytest for running tests and httpx to test fastapi endpoints
            - name: Installing the dependencies 
              run: |
                python -m pip install --upgrade pip
                pip install flake8 pytest httpx
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            # Step 4: Lint with Flake 8 to check for syntax errors and undefined names
            - name: Lint with Flake8 
              run: |
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            # Step 5: Running test using pytest and the test file is in test/test_main folder
            - name: Testing with Pytest
              run: |
                pytest -v --disable-warnings --maxfail=1
